[package]
name = "slopio"
version = "0.1.0"
edition = "2024"
license = "MIT OR 0BSD"

[dependencies]
bytes = "1.10.1"
memchr = "2.7.4"
tokio = { version = "1.43.0", features = ["io-util", "macros", "rt"] }
