[package]
name = "compliance"
version = "0.1.0"
edition = "2024"
license = "MIT OR 0BSD"

[dependencies]
chrono = { version = "0.4.39", default-features = false, features = ["clock", "serde", "std"] }
serde = { version = "1.0.218", features = ["derive"] }
